apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-app.name" . }}
  labels:
    {{- include "admin-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admin-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-app.name" . }}
    spec:
      containers:
        - name: admin-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
