apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-ecommerce.fullname" . | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: "{{ include "admin-ecommerce.name" . }}"
    helm.sh/chart: "{{ include "admin-ecommerce.chart" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "Helm"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "admin-ecommerce.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "admin-ecommerce.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: admin-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default "IfNotPresent" }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default 3000 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort | default 3000 }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort | default 3000 }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | default "{}" | nindent 12 }}