apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ecommerce-ingress
  namespace: production
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: app.e-commerce-app-host.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-ecommerce
                port:
                  number: 3000
