name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker already exists on GitHub runners
      - name: Verify Docker
        run: docker version

      # Build image for both push and PR
      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_REGISTRY }}/authecommerce:${{ github.sha }}
          docker build -t $IMAGE .

      # Login ONLY on push (not PR)
      - name: Log in to Docker registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Push ONLY on push
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          IMAGE=${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
          docker push $IMAGE
